# Generated by Django 5.0.2 on 2025-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='accounts_ex_user_id_0d6621_idx',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'date')},
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(default='api', max_length=50),
        ),
        migrations.AddField(
            model_name='userexchangerate',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['date'], name='accounts_ex_date_af043a_idx'),
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='user',
        ),
    ]
