# Generated by Django 5.0.2 on 2025-05-27 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_exchangerate_accounts_ex_user_id_0d6621_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_platform_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='source',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='currency',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['user', 'is_active'], name='accounts_cu_user_id_09c763_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_platform_currency'], name='accounts_cu_is_plat_a99bf7_idx'),
        ),
    ]
