# Generated by Django 5.0.2 on 2025-05-27 01:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_currency_is_platform_currency_currency_source_and_more'),
        ('transactions', '0003_alter_transaction_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('base_currency_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('rate_source', models.CharField(choices=[('USER', 'User Custom Rate'), ('PLATFORM', 'Platform Default Rate')], max_length=10)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='accounts.account')),
                ('destination_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_transfers', to='accounts.currency')),
                ('destination_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_transfer', to='transactions.transaction')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='accounts.account')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transfers', to='accounts.currency')),
                ('source_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transfer', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
                ('user_exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='accounts.userexchangerate')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.transfer'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transfer'], name='transaction_transfe_5e36a3_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_b3882e_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['source_account', 'destination_account'], name='transaction_source__2d5f42_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='transaction_status_fc2f55_idx'),
        ),
    ]
